services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4:6.9
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: nonoshita4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: samplepass
    ports:
      - "8083:80"
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin4-data:
