services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8085:8080"
    volumes:
      - .:/code
volumes:
  db-data:
